Profile fix
Inertia-Lighting/discord-bot pull request #471
Opened 2024-07-27 20:24 UTC by chessebuilderman

2024-07-27 20:25 UTC, chessebuilderman commented
Fuck it, ima just put this shit into master

2024-07-28 14:26 UTC, DaRealFrost commented
There seems to be an error:

```
#10 [5/6] RUN npm run build
#10 0.304 
#10 0.304 > discord-bot@3.0.0 build
#10 0.304 > npm run clean && tsc --build
#10 0.304 
#10 0.462 
#10 0.462 > discord-bot@3.0.0 clean
#10 0.462 > run-script-os
#10 0.462 
#10 0.644 
#10 0.644 > discord-bot@3.0.0 clean:linux
#10 0.644 > rm -rf ./dist
#10 0.644 
#10 3.920 src/custom_interactions/chat_input/add_user_identity.ts(117,15): error TS6133: 'user_update_filter' is declared but its value is never read.
#10 ERROR: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
------
 > [5/6] RUN npm run build:
0.304 
0.462 
0.462 > discord-bot@3.0.0 clean
0.462 > run-script-os
0.462 
0.644 
0.644 > discord-bot@3.0.0 clean:linux
0.644 > rm -rf ./dist
0.644 
3.[92](https://github.com/Inertia-Lighting/discord-bot/actions/runs/10126326866/job/28014712309?pr=471#step:3:93)0 src/custom_interactions/chat_input/add_user_identity.ts(117,15): error TS6133: 'user_update_filter' is declared but its value is never read.
------
dockerfile:13
--------------------
  11 |     
  12 |     # Build the bot
  13 | >>> RUN npm run build
  14 |     
  15 |     # Create tmp directory
--------------------
ERROR: failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
Error: Process completed with exit code 1.
```

2024-07-28 14:36 UTC, DaRealFrost requested changes
Please apply the changes were comments have been put. 😊

2024-07-28 14:36 UTC, DaRealFrost commented on src/common/handlers/user_profile_handler.ts
> +        viewable: true, // only fetch viewable products
Make it only return purchasable/viewable products

```ts
// Only fetch purchasable/viewable products
viewable: true,
purchasable: true,
```

2024-07-28 14:36 UTC, DaRealFrost commented on src/custom_interactions/chat_input/add_user_identity.ts
> -        required_access_level: CustomInteractionAccessLevel.Admins,
Keep this because it will only be used in a few specific cases (also we don't want it to be abused, in most cases at least one admin+ is available to help):

```ts
required_access_level: CustomInteractionAccessLevel.Admins,
```

2024-07-28 14:36 UTC, DaRealFrost commented on src/custom_interactions/chat_input/add_user_identity.ts
remove the blow as it is no longer used for the add feature:

```ts
        // create the update filter based on the provided information
        const user_update_filter = {
            'identity.discord_user_id': new_discord_id,
            'identity.roblox_user_id': new_roblox_id,
        };
```

2024-07-28 15:01 UTC, DaRealFrost approved these changes

2024-08-14 23:41 UTC, dr4wn approved these changes
lgtm

2024-08-17 17:18 UTC, merged